---

- name: disk durumuna bak
  shell: "df -h /"
  args:
    executable: "/bin/bash"
  register: disk 

- name: disk durumunu göster
  debug:
    msg: "{{disk.stdout_lines }}"

- name: RedHat rsyslog kurma
  yum:
    name: rsyslog
    state: present
  when: ansible_distribution_major_version == "7"

- name: RedHat rsyslog kurma
  dnf:
    name: rsyslog
    state: present
  when: ansible_distribution_major_version == "8"

- name: rsyslog service restart
  service: "name=rsyslog state=restarted" 
