---

- name: check disk status
  shell: "df -h /"
  args:
    executable: "/bin/bash"
  register: disk 

- name: show disk status
  debug:
    msg: "{{disk.stdout_lines }}"

- name: install rsyslog on Ubuntu
  apt:
    name: rsyslog
    state: present

- name: restart rsyslog service
  service: "name=rsyslog state=restarted" 
