---
- name: install apache2 webserver
  apt:
    name: apache2
    state: present

- name: customize index.html of apache2
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache2

- name: add value apache2
  copy:
    content: "{{ apache2 }}"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache2

- name: download apache2 config file
  fetch:
    src: /var/www/html/index.html
    dest: /tmp/index.html
    flat: yes
